### ISSUE TITLE
安装了latest-v4 但升级v4 pro的时候。paste 黏贴功能失效。

### ISSUE THREAD

**Issue by yanbinc** [dzhuang/tinymediamanager-docker#12]
安装了latest-v4 但升级v4 pro的时候。paste 黏贴功能失效。

很长一段验证码，不能黏贴的话就验证不了了。

**Comment by yanbinc** [comment]
补充，别的程序的paste 功能都是好的。但在chome里面tmm界面就是不行（地址栏粘贴都是没有问题。）。我也换了别的浏览器。一样。

**Comment by dzhuang** [comment]
这个应该是upstream的问题，请到 https://github.com/romancin/tinymediamanager-docker 去问，抱歉，我本人没有试过升级到pro.
