### ISSUE TITLE
我使用了:v4.3.8.1标签，但是安装之后还是4.2.8版本

### ISSUE THREAD

**Issue by 5536086** [dzhuang/tinymediamanager-docker#13]
我使用了:v4.3.8.1标签，但是安装之后还是4.2.8版本

**Comment by dzhuang** [comment]
你是说在原有的config目录上pull新的image吧？这个问题我也发现了，这是原repo的问题。

**Comment by 5536086** [comment]
> 

我是删了容器和镜像重新拉取的，你的意思是需要把映射目录也全部删掉是吗

**Comment by dzhuang** [comment]
[这几行](https://github.com/romancin/tinymediamanager-docker/blob/f27cd71b7b9b1e48a9f1007fcf67bf4d91afa3a4/rootfs/etc/cont-init.d/tmm.sh#L13-L17)的意思，就是如果`/config/tmm.jar`不存在，它才会复制一份新的过来，所以升级image之前，要把这个文件删除.

**Comment by dzhuang** [comment]
有时间我可以patch一下.

**Comment by dzhuang** [comment]
应该已经修复，请使用latest-v4或v4.3.8.1标签.
