### ISSUE TITLE
群晖做了反代，但是域名无法访问，其他同操作可访问，没有配置https，也没设置密码，用域名访问就是一直转圈。and 粘贴中文不好使

### ISSUE THREAD

**Issue by Biiddd** [dzhuang/tinymediamanager-docker#15]

**Comment by dzhuang** [comment]
本地访问成功？

**Comment by Biiddd** [comment]
> 本地访问成功？

成功的

**Comment by Biiddd** [comment]
![Snipaste_2023-03-07_22-14-13](https://user-images.githubusercontent.com/110301013/223447920-4c94ef64-7f0c-482e-9745-fd5f3bb715dc.png)
![Snipaste_2023-03-07_22-11-57](https://user-images.githubusercontent.com/110301013/223447955-be9d220b-2c48-47ab-9011-33fc7c8e4a88.png)

**Comment by dzhuang** [comment]
那你的问题和这个image没什么关系。我不记得当时怎么弄的了，下面是我的tmm.conf的片段:
    
    server {
	    listen 80;
	    listen 443 ssl http2;

	server_name tmm.example.com;

      if ($scheme = http) {
          rewrite ^ https://$host$request_uri? permanent;  # enforce https
      }

	ssl_certificate   /etc/nginx/cert/example.pem;
	ssl_certificate_key  /etc/nginx/cert/example..key;
	ssl_session_timeout 5m;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;

	location / {
			proxy_redirect off;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_pass http://127.0.0.1:8080;
	}

	location /websockify {
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_pass http://127.0.0.1:8080;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_read_timeout 86400;
	}

        access_log off;
    }

这样是可以的，大概率和websockify有关系
