### ISSUE TITLE
tmm版本问题

### ISSUE THREAD

**Issue by kiddyyang** [dzhuang/tinymediamanager-docker#16]
用 "latest" tag拉取后，tmm版本为3.1.16.1，请问如何能升级到最新的3.1.18？谢谢

**Comment by dzhuang** [comment]
upstream的版本号加了develop-前缀，并非正式发布，所以我这里还不支持。你可以改一下dockerfile，自己Build一个。如有疑问可以讨论。

**Comment by kiddyyang** [comment]
好的，感谢大佬。我用您这个版本目前的问题主要就是Rating会有3-4位的小数，不知道是不是3.1.16的问题

**Comment by dzhuang** [comment]
说明：v3已经不是upstream的主要努力方向，我个人目前也是使用v4了，虽然只有一个tmdb可以用，也基本够了；目前的v4(4.3.8.1)，tmdb评分正常。

p.s. 在张大妈上看到了你的评论，感觉你好像不知道可以pull使用latest-v4的tag?

**Comment by kiddyyang** [comment]
张大妈看到您的回复了，才发现是本尊，哈哈。
官方我pull的latest没有带-v4，我理解latest-v4应该是v4的最新版本，也没找到相关说明。
另外Pull了romancin/tinymediamanager:develop-v3.1也存在Rating小数点的问题。
最后请教下，官方v4的话好像还有50部影片的限制？

**Comment by dzhuang** [comment]
v4没有50部限制，只是数据库只能用tmdb

**Comment by kiddyyang** [comment]
谢谢大佬回复，我试试v4
