### ISSUE TITLE
中文输入和粘贴问题

### ISSUE THREAD

**Issue by kiddyyang** [dzhuang/tinymediamanager-docker#17]
在刮削页面，无法输入中文；同时设置剪贴板内容为后，粘贴显示为乱码。如图，不知大佬是否有可能解决，谢谢
![image](https://github.com/dzhuang/tinymediamanager-docker/assets/11471064/a42ff3d4-25f3-4720-b864-50392116f599)

**Comment by dzhuang** [comment]
vnc的已知问题，无解。#3
