### ISSUE TITLE
剪切板无法粘贴中文

### ISSUE THREAD

**Issue by Smolder3955** [dzhuang/tinymediamanager-docker#3]
已知是VNC的问题，TigerVNC镜像也无法粘贴中文，能否集成中文输入法？

**Comment by dzhuang** [comment]
@efsg 这是个known issue，你能不能加一个试一下，然后开个pr

**Comment by zailushang2008** [comment]
是不是也没办法输入中文。。。。

**Comment by Smolder3955** [comment]
> 是不是也没办法输入中文。。。。

两种思路：
1. 把原镜像的XVNC换成TigerVNC
2. 加装中文输入法

但不管哪种方法重新编译镜像都很麻烦

**Comment by dzhuang** [comment]
vnc的中文输入一直是一个难题。。。

**Comment by 188334911** [comment]
同问，期待解决中文输入，能复制粘贴也好
