### ISSUE TITLE
镜像被删除了吗？

### ISSUE THREAD

**Issue by 5536086** [dzhuang/tinymediamanager-docker#5]
docker: Error response from daemon: manifest for dzhuang/tinymediamanager:v4-latest not found: manifest unknown: manifest unknown.

**Comment by dzhuang** [comment]
哦，我改天检查一下。建议不要用v4，刮削50次就要收费了


    docker pull dzhuang/tinymediamanager:latest

**Comment by 5536086** [comment]
嗯嗯，解决了，大佬，但是有个问题，设置的是简中，但是第一次刮削自动变成英文，需要再刮一次才是中文

**Comment by dzhuang** [comment]
> 嗯嗯，解决了，大佬，但是有个问题，设置的是简中，但是第一次刮削自动变成英文，需要再刮一次才是中文

你说的这个问题我没碰到，印象中重启服务就是中文了。

**Comment by dzhuang** [comment]
> docker: Error response from daemon: manifest for dzhuang/tinymediamanager:v4-latest not found: manifest unknown: manifest unknown.

这个是文档问题，在https://github.com/dzhuang/tinymediamanager-docker/commit/a2e5a27e53e5e71b9dfff091958a7efbc88ff370 解决了
