### ISSUE TITLE
latest-v4无法显示中文

### ISSUE THREAD

**Issue by 5536086** [dzhuang/tinymediamanager-docker#9]
中文显示为方块
![QQ截图20220809120204](https://user-images.githubusercontent.com/20472307/183561527-cb8081d5-8241-475a-916d-7a2de85c2bbf.png)

**Comment by tramp201** [comment]
同样的问题

**Comment by wudgaby** [comment]
我也一样. 什么原因呢?

**Comment by dzhuang** [comment]
感谢报告，已解决 (c85c6db6cf1256cd7122c43fa96327d297c004fc)，请下载最新的image.
